added footer and layout component folders, deleted svgs
getting errors so can’t continue: “Cannot read property 'toLowerCase' of undefined” and Warning: React.createElement: type is invalid -- expected a string (for built-
in components) or a class/function (for composite components) but got: undefin
ed. You likely forgot to export your component from the file it's defined in,
or you might have mixed up default and named imports.

Check your code at Layout.js:5.
    in Layout (at withLayout.js:38)
    in ThemeProvider (at withLayout.js:37)
    in _class (at _document.js?entry:9)
    in StyleSheetManager
    in Unknown
    in AppContainer
    in Container
    in div
    in App
TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (/Users/fiona/Projects/danielfariagall
ery/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2
304:27)